/***************************************************************************** 
 * Project: RooFit                                                           * 
 *                                                                           * 
 * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/ 

// Your description goes here... 

#include "Riostream.h" 

#include "RooZPtPdf.h" 
#include "RooAbsReal.h" 
#include "RooAbsCategory.h" 
#include <math.h> 
#include "TMath.h" 

//ClassImp(RooZPtPdf);

RooZPtPdf::RooZPtPdf(const char *name, const char *title, RooAbsReal & _zpt, RooAbsReal & _a, RooAbsReal & _b, RooAbsReal & _c, RooAbsReal & _d) :
						RooAbsPdf(name,title), zpt("zpt", "zpt", this, _zpt), a("a", "a", this, _a),
						b("b", "b", this, _b), c("c", "c", this, _c), d("d", "d", this, _d) {} 

RooZPtPdf::RooZPtPdf(const RooZPtPdf& other, const char* name) : 
						RooAbsPdf(other,name), zpt("zpt",this,other.zpt), a("a",this,other.a),
						b("b",this,other.b), c("c",this,other.c), d("d",this,other.d) {}



Double_t RooZPtPdf::evaluate() const { 
	// ENTER EXPRESSION IN TERMS OF VARIABLE ARGUMENTS HERE 
	Double_t logzpt = TMath::Log(zpt);
	return TMath::Exp(a + b*logzpt + c*logzpt*logzpt + d*logzpt*logzpt*logzpt);
	//return TMath::Exp(a*TMath::Cos(b*logzpt + c) + d);
}
